[project]
name = "ai-chat-gui"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datetime>=6.0",
    "openrouter>=0.1.1",
    "python-dotenv>=1.2.1",
    "requests>=2.32.5",
]
